### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by kumavis** [Rudd-O/qubes-vpn#4]
> Use the Qubes Manager to create a ProxyVM. Attach it to your system's ProxyVM, so you can restrict the traffic that the VPN VM itself generates.

Is this correct? It sounds like a mistake, but I could be wrong.
ProxyVM -> ProxyVM ?

**Comment by Rudd-O** [comment]
That is correct, but you can also attach the VPN VM to your NetVM if you don't care about firewalling the VPN VM..

**Comment by Rudd-O** [comment]
I wrote a bit more in the docs to clarify how the whole thing works and that you can in fact skip using a ProxyVM attached to the VPN VM.

**Comment by kumavis** [comment]
Thanks! :smile_cat:
